# Use a Node.js image for the frontend
FROM node:20.9.0 as frontend

WORKDIR /app
# Copy frontend-specific files
COPY . /app

WORKDIR /app/frontend
RUN npm install
RUN npm run build
RUN find ../gpt_code_ui/webapp/static -mindepth 1 ! -name '.gitignore' -delete
RUN rsync -av dist/ ../gpt_code_ui/webapp/static

CMD ["gptcode"]