name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Create env file'
      run: echo "${{ secrets.ENV_FILE }}" > .env
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ secrets.ACR }}":$(date +%s)
